[workspace]
members = [
    "ddbb_server",
    "ddbb_client",
    "ddbb_libs",
    "example",
    "temp",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

