[workspace]
members = [
    "ddbb_server",
    "ddbb_client",
    "ddbb_libs",
    "examples/connection_sever",
    "examples/connection_client",
    "omnipaxos_core",
    "omnipaxos_storage",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

